toolbar:
  - styleselect | bold italic | undo redo | insert | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent
  - image | link | linkimage | forecolor backcolor emoticons | preview
plugins:
  - image
  - link
  - advlist
  - autolink
  - lists
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - fullscreen
  - insertdatetime
  - media
  - nonbreaking
  - save
  - table
  - contextmenu
  - directionality
  - emoticons
  - template
  - paste
  - textcolor
  - colorpicker
  - textpattern
  - imagetools
  - codesample
  - toc
